[SAC-217][SQL] Change strategy on accessing spark-sql-kafka to reflection (#218)
## What changes were proposed in this pull request?

We found that current approach (`spark-sql-kafka` as `provided` scope) sometimes doesn't work and 
 throw NoClassDefFoundError (e.g. see #217). Instead of letting end users deal with classloader stuffs, this patch proposes to change the approach - accessing `spark-sql-kafka` module via reflection, so that they just need to be loaded in thread context classloader.

This patch also removes custom patches for Kafka - I realized we can touch constructor parameters which are `values`, via reflection.

## How was this patch tested?

* Modified UTs which show custom patch is not needed even for batch query.
* Manual tests for both batch query and streaming query

> batch query

```
val sourceTopics = Seq("sparksource1sac217", "sparksource2sac217")
val sourceTopics2 = Seq("sparksource2sac217", "sparksource3sac217")

val customClusterName = "custom_cluster"

val df = spark.read.format("kafka")
  .option("kafka.bootstrap.servers","localhost:9027")
  .option("subscribe", sourceTopics.mkString(","))
  .option("kafka.atlas.cluster.name", customClusterName)
  .option("startingOffsets", "earliest")
  .load()

val assignForDf2 = """{"sparksource2sac217": [0, 1, 2, 3, 4], "sparksource3sac217": [0, 1, 2, 3, 4]}"""

val df2 = spark.read.format("kafka")
  .option("kafka.bootstrap.servers", "localhost:9027")
  .option("assign", assignForDf2)
  .option("startingOffsets", "earliest")
  .load()

df.union(df2).write.mode("append").saveAsTable("sac_217_2")
```

![Screen Shot 2019-04-23 at 11 29 22 AM](https://user-images.githubusercontent.com/1317309/56549362-8a98ba00-65bd-11e9-92ab-07355cff2a20.png)
![Screen Shot 2019-04-23 at 11 29 43 AM](https://user-images.githubusercontent.com/1317309/56549365-8a98ba00-65bd-11e9-896f-8dd2a5acc10e.png)
![Screen Shot 2019-04-23 at 11 29 50 AM](https://user-images.githubusercontent.com/1317309/56549366-8a98ba00-65bd-11e9-95e1-414abd0d3f83.png)
![Screen Shot 2019-04-23 at 11 29 56 AM](https://user-images.githubusercontent.com/1317309/56549367-8b315080-65bd-11e9-9319-1772787083a3.png)

> streaming query

```
val bootstrapServers = "localhost:9027"
val checkpointLocation = "/tmp/mykafka3"
val sourceTopics = Seq("sparksource1sac217", "sparksource2sac217").mkString(",")
val sourceTopics2 = Seq("sparksource2sac217", "sparksource3sac217").mkString(",")
val targetTopic = "sparksinksac217"

val df = spark.readStream.format("kafka").option("kafka.bootstrap.servers", bootstrapServers).option("subscribe", sourceTopics).option("startingOffsets", "earliest").option("kafka.atlas.cluster.name", "source").load()

val df2 = spark.readStream.format("kafka").option("kafka.bootstrap.servers", bootstrapServers).option("subscribe", sourceTopics2).option("startingOffsets", "earliest").load()

df.union(df2).writeStream.format("kafka").option("kafka.bootstrap.servers", bootstrapServers).option("checkpointLocation", checkpointLocation).option("topic", targetTopic).option("kafka.atlas.cluster.name", "sink").start()
```

![Screen Shot 2019-04-23 at 11 24 50 AM](https://user-images.githubusercontent.com/1317309/56549405-a69c5b80-65bd-11e9-8c1e-e375e82dc14e.png)
![Screen Shot 2019-04-23 at 11 25 03 AM](https://user-images.githubusercontent.com/1317309/56549407-a734f200-65bd-11e9-90d0-6745e24527f3.png)
![Screen Shot 2019-04-23 at 11 32 07 AM](https://user-images.githubusercontent.com/1317309/56549423-b1ef8700-65bd-11e9-84ec-5cd67907f893.png)
![Screen Shot 2019-04-23 at 11 32 18 AM](https://user-images.githubusercontent.com/1317309/56549425-b2881d80-65bd-11e9-8d70-5cc76c2eaee0.png)

This closes #217