[SAC-128][SQL] Cyclic `INSERT INTO` should not generate outbound link (#129)
## What changes were proposed in this pull request?

Atlas doesn't support cycle. Currently, Spark fails like the following. Hive omits the out-going edge to avoid this situation.

```scala
scala> sql("insert into t select * from t")
18/11/20 19:18:24 WARN RestAtlasClient: Failed to create entities
java.lang.IllegalStateException: Fail to get create entities
        at com.hortonworks.spark.atlas.RestAtlasClient.doCreateEntities(RestAtlasClient.scala:73)
```

**AFTER**

![cycle](https://user-images.githubusercontent.com/9700541/48873766-954bea80-eda4-11e8-8ff6-0fbb23fa6d45.png)


## How was this patch tested?

- Pass the Travis CI with newly added test cases.
- Also, this is verified with Apache Atlas 1.1.0 and Apache Spark 2.4.0.

This closes #129